# Generated by Django 4.1 on 2022-08-29 15:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('account_name', models.CharField(max_length=14, null=True)),
                ('account_type', models.CharField(max_length=14, null=True)),
                ('password', models.CharField(max_length=8, null=True)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15, null=True)),
                ('lastname', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(default=1, max_length=100, null=True)),
                ('emails', models.EmailField(max_length=30, null=True)),
                ('phonenumber', models.CharField(max_length=10, null=True)),
                ('age', models.IntegerField(max_length=5, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('profile_picture', models.ImageField(upload_to='profile_picture/')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(default=django.utils.timezone.now)),
                ('receipt_description', models.TextField()),
                ('name', models.CharField(max_length=12, null=True)),
                ('balance', models.BigIntegerField()),
                ('amount', models.BigIntegerField()),
                ('file', models.FileField(upload_to='Wallet/')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField(max_length=1, null=True)),
                ('balance', models.BigIntegerField()),
                ('pin', models.PositiveSmallIntegerField()),
                ('currency', models.CharField(max_length=8, null=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wallet_customer', to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.IntegerField()),
                ('transaction_amount', models.BigIntegerField()),
                ('transaction_charges', models.IntegerField()),
                ('transaction_date_time', models.DateField(default=django.utils.timezone.now)),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_destination_account', to='wallet.account')),
                ('origin_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_origin_account', to='wallet.account')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_receipt', to='wallet.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Thirdparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18, null=True)),
                ('currency', models.CharField(max_length=200, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Thirdparty_account', to='wallet.account')),
                ('transaction_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Thirdparty_transaction', to='wallet.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_reward', models.DateTimeField(default=django.utils.timezone.now)),
                ('description_of_reward', models.TextField()),
                ('reward_points', models.SmallIntegerField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reward_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=20, null=True)),
                ('read_unread_status', models.CharField(max_length=20, null=True)),
                ('date_and_time', models.DateField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notification_recipient', to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField()),
                ('loan_type', models.CharField(max_length=28, null=True)),
                ('amount', models.IntegerField()),
                ('loan_status', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('purpose_of_the_loan', models.CharField(max_length=200, null=True)),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('payment_due_date', models.DateField(default=django.utils.timezone.now)),
                ('loan_balance', models.IntegerField()),
                ('interest_rate', models.SmallIntegerField()),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_customer', to='wallet.customer')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(default=django.utils.timezone.now)),
                ('signature', models.ImageField(upload_to='signature')),
                ('issuer', models.CharField(max_length=20, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card_wallet', to='wallet.account')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account_wallet', to='wallet.wallet'),
        ),
    ]
