# Generated by Django 4.1 on 2022-08-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='Account',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='Wallet',
            new_name='wallet',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='Wallet',
            new_name='wallet',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='Wallet',
            new_name='wallet',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='Customer',
            new_name='customer',
        ),
    ]
