# Generated by Django 4.0.6 on 2022-07-31 04:31

from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_account_card_loan_notification_receipt_reward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='adress',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='address',
        ),
        migrations.AddField(
            model_name='loan',
            name='date_issued',
            field=models.DateTimeField(default=datetime.now),
        ),
        migrations.AddField(
            model_name='loan',
            name='payment_due_date',
            field=models.DateTimeField(default=datetime.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.now),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateTimeField(default=datetime.now),
        ),
        migrations.AddField(
            model_name='reward',
            name='date_of_reward',
            field=models.DateTimeField(default=datetime.now),
        ),
    ]
