# Generated by Django 4.0.6 on 2022-07-31 04:58

from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0004_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='date_created',
            field=models.DateField(default=datetime.now),
        ),
    ]
