# Generated by Django 4.0.6 on 2022-07-31 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0005_remove_wallet_balance_alter_wallet_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_issued',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='loan',
            name='payment_due_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reward',
            name='date_of_reward',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
