# Generated by Django 4.0.6 on 2022-08-02 01:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0006_alter_card_date_issued_alter_card_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='Account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.account'),
        ),
        migrations.AddField(
            model_name='card',
            name='Wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.wallet'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='Wallet',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Wallet.wallet'),
        ),
        migrations.AddField(
            model_name='loan',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.customer'),
        ),
        migrations.AddField(
            model_name='reward',
            name='Wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.wallet'),
        ),
        migrations.AddField(
            model_name='reward',
            name='reward_points',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='Account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.account'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='name',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Receipt',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Account_b', to='Wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Account_a', to='Wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_charges',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='card',
            name='serial_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='isactive',
            field=models.BooleanField(max_length=1, null=True),
        ),
    ]
